#! /bin/sh

COOPERARI_VERSION=$($(dirname $0)/cversion)
COOPERARI_HOME=$(cd $(dirname $0)/.. && pwd)
COOPERARI_JAR=$COOPERARI_HOME/lib/cooperari-$COOPERARI_VERSION.jar

ASPECTJRT_JAR=$(find "$COOPERARI_HOME/lib" -name 'aspectjrt*.jar')

java -cp "$ASPECTJRT_JAR:$COOPERARI_JAR:$CLASSPATH" org.cooperari.tools.csetup $*



