#! /bin/sh

if [ "$CINSTR_HOME" = "" ] ; then CINSTR_HOME=$HOME/.cooperari
fi

COOPERARI_VERSION=$($(dirname $0)/cversion)
COOPERARI_HOME=$(cd $(dirname $0)/.. && pwd)
COOPERARI_JAR=$COOPERARI_HOME/lib/cooperari-$COOPERARI_VERSION.jar

ASPECTPATH="$CINSTR_HOME/$1-cooperari.jar"
AGENT_JAR=$(find "$COOPERARI_HOME/lib" -name 'aspectjweaver*.jar')
CLASSPATH="$ASPECTPATH:$AGENT_JAR:$COOPERARI_JAR:$CLASSPATH"

java -classpath "$CLASSPATH" \
   "-javaagent:$AGENT_JAR" \
   "-Daj.class.path=$CLASSPATH" \
   org.junit.runner.JUnitCore \
   "$*"
