name: CI
on:
  push:
    branches:
      - 'master'
jobs:
  supported-jdk:
    name: ${{ matrix.title }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: "JDK 8"
            java: "8"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout from Git'
        uses: actions/checkout@v2
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"
      - name: 'Display JDK version'
        run: java -version
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: 'Test'
        run: mvn -B package
